### ISSUE TITLE
GPS sensor works, but "Invalid" in GUI

### ISSUE THREAD

**Issue by JaBecker** [CosmicLabDESY/muonic#24] opened 2016-10-28 08:09 UTC
Steps to reproduce:

Install Muonic 2.1.2 on Ubuntu 14.04 on the provided laptop
Attach GPS sensor to DAQ box and wait for signal (green LED shows enough satellites)
open Muonic and go to "GPS output" and press "Show GPS"
Result: STATUS: Invalid, Checksum: Error, Satellites: 0

But if the command "DG" is entered as an DAQ command, correct data is displayed including the number of satellites. Also, the ChkSumErr counter is 0.

Note: This is a crosspost from https://github.com/achim1/muonic/issues/79 as this repository is more active.

**Comment by JaBecker** [comment] 2016-11-07 09:00
I tested the latest version from the develop branch, the error is still persistent in that version.

To me, it looks like some sort of parsing error as the "DG" command shows a valid status ("A (valid)") and no ChecksumError.

**Comment by hpbretz** [comment] 2016-11-09 15:49
Please try version 2.1.3 on pypi now, it should be fixed. It was indeed a parsing error, caused by improper handling of DAQ messages longer than one line.

**Closed as completed by hpbretz** 2016-11-09 15:49 UTC
